import type { LessonType } from '../types/core';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { coursesApi } from '../api/courses';
import { examsApi } from '../api/exams';
import { forumApi } from '../api/forum';
import { learningApi } from '../api/learning';
import { materialsApi } from '../api/materials';
import { authApi } from '../api/auth';
import { notificationsApi, executionApi } from '../api/services';
import type { CourseRequest, CourseModuleRequest, LessonRequest, LessonProgressRequest, ExamRequest, ExamAnswerRequest, ForumTopicRequest, ForumPostRequest, PostReactionRequest, AskRequest } from '../types/requests';
export const useLogin = () => useMutation({ mutationFn: authApi.login });
export const useRegister = () => useMutation({ mutationFn: authApi.register });
export const useCourses = (enabled = true) => useQuery({ queryKey: ['courses'], queryFn: ({signal}) => coursesApi.catalog(signal), enabled });
export const useMyCourses = (enabled = true) => useQuery({queryKey:['courses','mine'],queryFn:({signal})=>coursesApi.mine(signal),enabled});
export const useSearchCourses = (query: string, enabled = true) => useQuery({ queryKey: ['courses','search',query], queryFn: ({signal}) => coursesApi.search(query, signal), enabled });
export const useCourse = (id: number) => useQuery({ queryKey: ['courses',id], queryFn: ({signal}) => coursesApi.get(id, signal) });
function useCoreMutation<T, R>(mutationFn: (value: T) => Promise<R>, key: string) {
  const client = useQueryClient();
  return useMutation({ mutationFn, onSuccess: () => client.invalidateQueries({queryKey: [key]}) });
}
export const useCreateCourse = () => useCoreMutation((data: CourseRequest) => coursesApi.create(data),'courses');
export const usePublishCourse = () => useCoreMutation(coursesApi.publish,'courses');
export const useEnrollment = () => useCoreMutation(coursesApi.enroll,'courses');
export const useAddModule = (id: number) => useCoreMutation((data: CourseModuleRequest) => coursesApi.addModule(id,data),'courses');
export const useAddLesson = <T extends LessonType>(id: number) => useCoreMutation((data: LessonRequest<T>) => coursesApi.addLesson(id,data),'courses');
export const useCompleteLesson = () => useCoreMutation((data: LessonProgressRequest) => coursesApi.completeLesson(data),'progress');
export const useCreateExam = (id: number) => useCoreMutation((data: ExamRequest) => examsApi.create(id,data),'courses');
export const useGenerateExam = () => useCoreMutation(examsApi.generate,'courses');
export const useStartAttempt = () => useCoreMutation(examsApi.startAttempt,'attempts');
export const useSubmitAttempt = (id: number) => useCoreMutation((data?: ExamAnswerRequest[]) => examsApi.submitAttempt(id,data),'attempts');
export const useAttempt = (id: number) => useQuery({queryKey: ['attempts',id], queryFn: ({signal}) => examsApi.getAttempt(id,signal)});
export const useTopics = (id: number) => useQuery({queryKey: ['forum','course',id], queryFn: ({signal}) => forumApi.topics(id,signal)});
export const useTopic = (id: number) => useQuery({queryKey: ['forum','topic',id], queryFn: ({signal}) => forumApi.topic(id,signal)});
export const useCreateTopic = (id: number) => useCoreMutation((data: ForumTopicRequest) => forumApi.createTopic(id,data),'forum');
export const useCreatePost = (id: number) => useCoreMutation((data: ForumPostRequest) => forumApi.createPost(id,data),'forum');
export const useAddReaction = (id: number) => useCoreMutation((data: PostReactionRequest) => forumApi.react(id,data),'forum');
export const useRemoveReaction = () => useCoreMutation(forumApi.removeReaction,'forum');
export const useProgress = (id: number) => useQuery({queryKey: ['progress',id], queryFn: ({signal}) => learningApi.progress(id,signal)});
export const useAnalytics = (id: number) => useQuery({queryKey: ['analytics',id], queryFn: ({signal}) => learningApi.analytics(id,signal)});
export const useAsk = (id: number) => useMutation({mutationFn: (data: AskRequest) => learningApi.ask(id,data)});
export const useUploadMaterial = (id: number) => useCoreMutation((file: File) => materialsApi.upload(id,file),'courses');
export const useDownloadMaterial = () => useMutation({mutationFn: materialsApi.download});
export const useExecuteCode = () => useMutation({mutationFn: executionApi.execute});
export const useNotifications = (id: number) => useQuery({queryKey: ['notifications',id], queryFn: ({signal}) => notificationsApi.list(id,signal)});
export const useReadNotification = (userId: number) => useCoreMutation((id: string) => notificationsApi.markRead(id,userId),'notifications');
