import { Link } from 'react-router-dom';
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { useAnalytics } from '../hooks/useApi';
import { Back, PageHeading, Loading, QueryError, useRouteId, InvalidId, numberLabel } from '../components/Page';
import { Unavailable } from '../components/Feedback';
export function AnalyticsPage(){const id=useRouteId('courseId');return id ? <Analytics id={id}/> : <InvalidId/>;}
function Analytics({id}: {id:number}){
 const query=useAnalytics(id);if(query.isLoading)return <Loading/>;if(query.error)return <QueryError error={query.error} retry={()=>void query.refetch()}/>;if(!query.data)return null;const data=query.data;
 return <><Back to={`/courses/${id}`}>К курсу</Back><PageHeading eyebrow="АНАЛИТИКА" title={data.courseTitle || 'Аналитика курса'} description="Прогресс и результаты студентов."><Link className="text-primary underline" to={`/reports/courses/${id}`}>Результаты учеников</Link></PageHeading><div className="stats-grid four-stats">{[['Студентов',numberLabel(data.totalStudents)],['Завершили курс',numberLabel(data.completedStudents)],['Средний прогресс',numberLabel(data.averageProgress,'%')],['Средний балл',numberLabel(data.averageExamScore)]].map(([label,value])=><div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{!data.lessons?.length ? <Unavailable title="Статистики по урокам пока нет" message="Она появится, когда сервер предоставит данные."/> : <section className="panel"><h2>Завершение уроков</h2><div className="chart-wrap" role="img" aria-label="Процент студентов, завершивших каждый урок; точные значения в таблице ниже"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.lessons} layout="vertical" margin={{left:0,right:24,top:12,bottom:12}}><CartesianGrid stroke="var(--border)" horizontal={false}/><XAxis type="number" domain={[0,100]} tickFormatter={v=>`${v}%`} stroke="var(--muted-foreground)"/><YAxis type="category" dataKey="lessonTitle" width={120} tick={{fontSize:12}} stroke="var(--muted-foreground)"/><Tooltip contentStyle={{background:'var(--background)',border:'1px solid var(--border)',color:'var(--foreground)'}}/><Bar dataKey="completionPercent" name="Завершение, %" fill="#6371ec" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div><div className="table-scroll"><Table><TableCaption className="sr-only">Завершение уроков студентами</TableCaption><TableHeader><TableRow><TableHead>Урок</TableHead><TableHead>Завершили</TableHead><TableHead>Всего студентов</TableHead><TableHead>Завершение</TableHead></TableRow></TableHeader><TableBody>{data.lessons.map(lesson=><TableRow key={lesson.lessonId}><TableCell>{lesson.lessonTitle || `Урок #${lesson.lessonId}`}</TableCell><TableCell>{numberLabel(lesson.completedStudents)}</TableCell><TableCell>{numberLabel(lesson.totalStudents)}</TableCell><TableCell>{numberLabel(lesson.completionPercent,'%')}</TableCell></TableRow>)}</TableBody></Table></div></section>}</>;
}
