import { RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAttempt } from '../hooks/useApi';
import { PageHeading, Loading, QueryError, useRouteId, InvalidId, numberLabel, statusLabel, dateLabel } from '../components/Page';
export function AttemptPage(){const id=useRouteId('attemptId');return id ? <Attempt id={id}/> : <InvalidId/>;}
function Attempt({id}: {id:number}){
 const query=useAttempt(id);if(query.isLoading)return <Loading/>;if(query.error)return <QueryError error={query.error} retry={()=>void query.refetch()}/>;if(!query.data)return null;const data=query.data;
 return <><PageHeading eyebrow={`ЭКЗАМЕН #${data.examId}`} title={`Результат попытки #${data.attemptId}`} description={statusLabel(data.status)}><Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}><RefreshCw/>Обновить</Button></PageHeading><div className="stats-grid"><div className="stat-card"><span>Итоговый балл</span><strong>{numberLabel(data.totalScore)}</strong></div><div className="stat-card"><span>Начало</span><strong className="date-stat">{dateLabel(data.startedAt)}</strong></div><div className="stat-card"><span>Завершение</span><strong className="date-stat">{dateLabel(data.finishedAt)}</strong></div></div><div className="space-y-5">{data.answers?.map((answer,index)=><section className="panel" key={answer.questionId}><div className="section-heading"><h2>Вопрос {index+1}</h2><span>{numberLabel(answer.score)} / {numberLabel(answer.maxScore)} баллов</span></div><p className="prose-text">{answer.question || 'Текст вопроса недоступен.'}</p><h3 className="subheading">Ответ ученика</h3><p className="answer-text">{answer.answer || 'Ответ не указан.'}</p>{answer.feedback && <><h3 className="subheading">Обратная связь AI</h3><p className="prose-text">{answer.feedback}</p></>}</section>)}</div>{!data.answers?.length && <p className="text-muted-foreground">Сервер пока не вернул подробные результаты.</p>}</>;
}
