import { Link } from 'react-router-dom';
import { BookOpen, CheckCircle2, ClipboardCheck } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import { useProgress } from '../hooks/useApi';
import { useAuth } from '../context/AuthContext';
import { PageHeading, Loading, QueryError, numberLabel, statusLabel, dateLabel } from '../components/Page';
import { Unavailable } from '../components/Feedback';
export function ProgressPage(){const {user}=useAuth();return user ? <StudentProgress userId={user.id}/> : <Unavailable title="Профиль недоступен"/>;}
function StudentProgress({userId}: {userId:number}){
 const query=useProgress(userId);const {user}=useAuth();
 if(query.isLoading)return <Loading/>;if(query.error)return <QueryError error={query.error} retry={()=>void query.refetch()}/>;
 const courses=query.data ?? [];const completed=courses.some(c=>c.completedLessons===null) ? null : courses.reduce((sum,c)=>sum+c.completedLessons!,0);const total=courses.some(c=>c.totalLessons===null) ? null : courses.reduce((sum,c)=>sum+c.totalLessons!,0);
 return <><PageHeading eyebrow="МОЁ ОБУЧЕНИЕ" title={user?.fullName ? `${user.fullName}, ваш прогресс` : 'Мой прогресс'} description="Ваши курсы, пройденные уроки и результаты экзаменов."><Button asChild variant="outline"><Link to="/courses">Каталог курсов</Link></Button></PageHeading>{!courses.length ? <Unavailable title="Начните с первого курса" message="После записи на курс здесь появится ваш прогресс."/> : <><div className="stats-grid"><div className="stat-card"><BookOpen/><span>Курсы</span><strong>{courses.length}</strong></div><div className="stat-card"><CheckCircle2/><span>Завершённые уроки</span><strong>{numberLabel(completed)} <small>/ {numberLabel(total)}</small></strong></div><div className="stat-card"><ClipboardCheck/><span>Попытки в отчёте</span><strong>{courses.reduce((n,c)=>n+(c.exams?.length??0),0)}</strong></div></div><div className="space-y-6">{courses.map(course=><section className="panel" key={course.courseId}><div className="section-heading"><Link to={`/courses/${course.courseId}`}><h2>{course.courseTitle || `Курс #${course.courseId}`}</h2></Link><strong>{numberLabel(course.progressPercent,'%')}</strong></div><Progress value={course.progressPercent == null ? null : Math.max(0,Math.min(100,course.progressPercent))} aria-label="Прогресс курса"/><p className="text-sm text-muted-foreground mt-3">Пройдено уроков: {numberLabel(course.completedLessons)} из {numberLabel(course.totalLessons)}</p>{!!course.exams?.length && <div className="report-list"><h3>Попытки экзаменов</h3>{course.exams.map((exam,index)=><div key={`${exam.examId}:${index}`} className="report-row"><span>{exam.examTitle || `Экзамен #${exam.examId}`}</span><span>{statusLabel(exam.status)}</span><strong>{numberLabel(exam.score)} баллов</strong></div>)}</div>}{!!course.lessons?.length && <details className="mt-5"><summary className="cursor-pointer text-sm">Уроки курса</summary><div className="report-list">{course.lessons.map(lesson=><div className="report-row" key={lesson.lessonId}><span>Урок #{lesson.lessonId}</span><span>{lesson.completedAt ? dateLabel(lesson.completedAt) : 'Не пройден'}</span><span>{numberLabel(lesson.score)} баллов</span></div>)}</div></details>}</section>)}</div></>}</>;
}
